[package]
name = "turtle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "2.7"
rand = "0.9"
sdl2 = { version = "0.37", features = ["bundled"] }
paste = "1.0"
clap = { version = "4.5", features = ["derive"] }