[package]
name = "turtle-web"
version = "0.1.0"
authors = ["Bernhard Lindner lindbe.pi22@stud.gera.dhge.de"]
edition = "2021"
description = "Webserver for turtle graphics programs"

[dependencies]
turtle = { path = ".." }
serde_json = "1.0"
parking_lot = "0.12"
actix-web = "4.10"